site_name: Gentry
site_url: http://gentry.monomelodies.nl/docs/
repo_url: https://github.com/monomelodies/gentry

pages:
- Home:
    - 'Quickstart': 'index.md'
- Writing tests:
    - 'The basics': 'writing/basics.md'
    - 'Complexer tests': 'writing/complex.md'
    - 'Sharing data': 'writing/sharing.md'
    - 'Unit tests': 'writing/unit.md'
    - 'Integration tests': 'writing/integration.md'
    - 'Acceptance tests': 'writing/acceptance.md'
    - 'Testing command line scripts': 'writing/cli.md'
    - 'Testing procedural code': 'writing/procedural.md'
- Generating tests:
    - 'About generated tests': 'generating/about.md'

